In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A


array([ 1.63500996, -0.78449843, -1.61721186,  1.10712975, -0.39989998,
        0.49784141,  1.19486889,  0.72584757,  0.08382564, -0.98419752])

In [7]:
B = np.random.randn(10)
B

array([-0.55197506,  2.26821829, -1.29486083,  0.17709189, -0.98473382,
        0.1130046 ,  0.219815  , -1.11697724,  0.32837396,  0.78613866])

In [8]:
np.add(A,B)

array([ 1.0830349 ,  1.48371986, -2.9120727 ,  1.28422164, -1.3846338 ,
        0.61084601,  1.41468388, -0.39112967,  0.4121996 , -0.19805886])

In [9]:
np.maximum(A,B)

array([ 1.63500996,  2.26821829, -1.29486083,  1.10712975, -0.39989998,
        0.49784141,  1.19486889,  0.72584757,  0.32837396,  0.78613866])

In [11]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True